####################################
# FEATURESET047 - UNDERCLOUD UPGRADE
# Based on featureset003
####################################

undercloud_generate_service_certificate: false
ssl_overcloud: false
undercloud_check_idempotency: true
undercloud_check_sanity: true
containerized_overcloud: false
containerized_overcloud_upgrade: false

# Force addition of overcloud-upgrade tag, although what will
# be performed is an undercloud upgrade instead.
mixed_upgrade: true

# Tripleo-upgrade specific parameters
use_tripleo_upgrade: true
undercloud_upgrade: true
target_upgrade_version: "master"
